### ISSUE TITLE
Compiler always compiles with APPLICATION as resource name

### ISSUE THREAD

**Issue by markwilliams1234** [JAM-Software/RibbonFramework#117]
This used to work and can't quite see what is wrong in the code now. I have two ribbons in my app. One has the default ResourceName "APPLICATION" and the other has the resource name "BUNDLE". They used to compile ok using the correct resource names, but not any longer. Not sure when the problem started unfortunately. 

I have had a look at the code to see if I can see where the problem arises, but can't quite figure it out.

Also, can't compile the designer proj any longer. Comes up with error:
[BRCC32 Error] UIRibbon.rc(1): Error Could not open input file C:party\drag.RC

**Comment by joachimmarder** [comment]
>Also, can't compile the designer proj any longer. Comes up with error:
>[BRCC32 Error] UIRibbon.rc(1): Error Could not open input file C:party\drag.RC

I don't see this here. And I can't find any reference to "Drag.rc" in the entire source code. Therefore I suspect a local change on your side.

**Comment by joachimmarder** [comment]
> One has the default ResourceName "APPLICATION" and the other has the resource name "BUNDLE". 
> They used to compile ok using the correct resource names, but not any longer. 

This is working fine here. Where / how do you specify the ribbon name?

**Comment by markwilliams1234** [comment]
> I don't see this here. And I can't find any reference to "Drag.rc" in the entire source code. Therefore I suspect a local change on your side.

Just downloaded the latest version today and tried to compile the designer.

**Comment by markwilliams1234** [comment]
> how do you specify the ribbon name?

My mistake. Didn't realise the resource name was set through the main menu. I was setting resource name of the TUIRibbon through the components ResourceName property and assumed this was being picked up when you open the ribbon designer by right clicking on the TUIRibbon component.

**Comment by joachimmarder** [comment]
> Just downloaded the latest version today 

Same here. I successfully tested this with RAD Studio 10.3 and 10.4 on a fresh checkout.

**Comment by markwilliams1234** [comment]
Still can't get a compile. Will be upgrading to 10.4 shortly and will try again then.

**Comment by joachimmarder** [comment]
Which RAD Studio version did you use?

**Comment by markwilliams1234** [comment]
Sorry. 10.3

**Comment by joachimmarder** [comment]
@markwilliams1234 : Is this issue still valid?

**Comment by joachimmarder** [comment]
No response from report, no repro steps => Close
