### ISSUE TITLE
Preview not working on Delphi 10.4

### ISSUE THREAD

**Issue by Andyk1234** [JAM-Software/RibbonFramework#120]
Seems to want a units (eg system) which is no longer included in the new version of Delphi.

RibbonMarkup.dpr(1) 
RibbonMarkup.dpr(1) Fatal: F1027 Unit not found: 'System' or binary equivalents (.dcu)

**Comment by joachimmarder** [comment]
`RibbonMarkup.dpr` is not a file that part of this project. Please provide more detailed repro steps.

**Comment by joachimmarder** [comment]
No response from reporter => Close
