### ISSUE TITLE
Quick Access Tool Bar error in DarkMode

### ISSUE THREAD

**Issue by Sucx01** [JAM-Software/RibbonFramework#123]
When switches to DarkMode, the Quick Access Tool Bar don’t display correctly. It is showed under the application title bar with incorrect color.

**Comment by joachimmarder** [comment]
Can you please post a screenhsot here?

This is how it looks like in TreeSize Free:
![grafik](https://github.com/JAM-Software/RibbonFramework/assets/10615289/21bc5afe-e1ab-4a09-8fb7-d46fa6157c99)

**Comment by Sucx01** [comment]
The first figures is the screenshot of demo application ‘\RibbonFramework\Samples\High Level\06 Text Pad’.
 
![image](https://github.com/user-attachments/assets/61a379f7-952e-4bf9-9643-2296be6c017f)

  The second one is from the same demo, but add a Delphi Style (Carbon.vsf) via TStyleManager.SetStyle('Carbon') function, not the Dark Mode of Windows Ribbon Framework itself.
  We can see that The Quick Access Toolbar (QAT) has disappeared from application’s title bar, and an additional blank line emerges under the title bar.
 
![image](https://github.com/user-attachments/assets/d48c2cd8-e764-4022-8665-ed8aa877daf8)

  I can't resolve this problem and need your help.
  P.s. how can we use Windows Ribbon Framework in Lazarus?
